### ISSUE TITLE
error fatal: wspiapi.h: No such file or directory  #    include <wspiapi.h>

### ISSUE THREAD

**Issue by Jentys** [eazarkman/nft-bot#1]
what wspiapi.h do you use?, i already tried adding such file in the include directory on Ming but didn't work

thanks for you hard work, i appreciate.

regards.

**Comment by eazarkman** [comment]
Hi Jentys pleased to see your comment. May you please share the messages you see from the compiler? 

FYI, I compiled the C/C++ code using 'g++' via the bash shell on  the Windows Subsystem for Linux (WSL2). 

gcc version 7.5.0 (Ubuntu 7.5.0-3ubuntu1~18.04)
